server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: FP
  datasource:
    url: jdbc:mariadb://localhost:3306/rent4u_clone
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  thymeleaf:
    cache: false
    enabled: true
minio:
  bucket:
    name: rent4u
  access:
    key: minioadmin
    secret: minioadmin
  url: http://127.0.0.1:9000

#logging:
#  level:
#    org.springframework.security: DEBUG
#  file:
#    name: application.log
#  logback:
#    rollingpolicy:
#      max-history: 90
#      max-file-size: 10MB
secret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
jwtExpiration: 360000